apiVersion: v1
kind: Service
metadata:
  name: chatbot
  namespace: like2share
  labels:
    app: chatbot
    tier: api
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: chatbot
